### PR TITLE
Add TypeScript support

### LINKED ISSUE #26: Add a basic `tsconfig.json` for full TypeScript support in the project.
TypeScript not only provides "type safety" for JavaScript code but in general helps maintaining standard development practices in a project. As such, right now is the best opportunity to add TypeScript support for the project since it can be quite difficult to get started up again later on when the project is moving ahead already.

For more reference on setting up a proper [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file, refer to it's official documentations: https://www.typescriptlang.org/tsconfig

### PR DESCRIPTION
**Pull request by siddhantk232**
## Description

- enable typescript in nextjs project
- adds a `tsconfig.json`

### Fixed issue(s): #

fixes #26

### Changes Include

-   [x] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)

### Checklist

-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Jarmos-san** [comment]
@siddhantk232 thanks for the contributions!

First off, to continue the discussion about `.nix` support for the project we had on Discord.

1. Hold up on those aspects for a separate PR in the future.
2. Since most of us don't about `nix` yet & it'll probably take a week or two to learn it well. So, let's have a discussion about it so that all of us are onboarded for using `nix`.

Also, there's an open PR #24 which will clean up the repository quite a lot. Once that's merged you might've to rebase your fork to pull in the latest changes. So, please hold on for a bit & I'll review your PR accordingly afterwords.

**Review by Jarmos-san — CHANGES_REQUESTED** [review]
Looks good imo. But before it's merged could you remove the changes you made to the `src/pages/index.js` & `yarn.lock` files? These changes could introduce potential merge conflicts on another PR #24.

**Comment by siddhantk232** [comment]
We should use either npm or yarn.

**Comment by Jarmos-san** [comment]
> We should use either npm or yarn.

Yes, we'll be using `npm`. #24 will be removing the redundant `yarn.lock`. The PR is awaiting a review from @varshney-himanshu since he was one of the guys who was actively working on the project earlier.

**Review by Jarmos-san — APPROVED** [review]

**Review by varshney-himanshu — APPROVED** [review]

**Pull request merged**
