### PR TITLE
Refactor code base & clean up unnecessary packages

### PR DESCRIPTION
**Pull request by afkcodes**
Just refactored some code & updated the packages.  will continue on this once my personal things get caught up.

### CODE REVIEW

**Comment by Jarmos-san** [comment]
Hey @afkcodes it's been a while since any progress has been made on any of the projects in the [developersIndia](https://github.com/developersIndia) GitHub org. We had a long discussion on what the future of any of the current & prospective projects in the org entails. So, please subscribe to any updates we share here or in our [Discord server](https://discord.gg/gUWQyCc2GN).

On that note, this repository needs to be cleaned up & refactored quite a lot, so let me know if you would still like to proceed ahead with the PR?

**Review by Jarmos-san — CHANGES_REQUESTED** [review]
Could you revert back the deleted files, move them under a `src` directory as described in https://nextjs.org/docs/advanced-features/src-directory. Also it would be nice if you could delete the TailwindCSS config file & remove any other unneeded dependencies except Next.js.

**Comment by afkcodes** [comment]
Yeah will do that, also I want to be an active contributor to the project, as this whole project goes dormant for a long time. This is the best way we can help beginners and others as well. I also checked reached out to folks but no response.

**Comment by Jarmos-san** [comment]
> Yeah will do that, also I want to be an active contributor to the project, as this whole project goes dormant for a long time. This is the best way we can help beginners and others as well. I also checked reached out to folks but no response.

Understandable. We had a long chat about the future of all current & prospect projects in the developersIndia community. So, we'll trying to revive contributions to the project once again this time with serious intent.

That said, please feel free to contribute to the project(s) as you see fit. Also do check out the [issue threads](https://github.com/developersIndia/developersIndia.in/issues), we're looking for a designer who can share a first iteration of the official landing page for the community. If you know someone who's willing to contribute to the project, let them know about it.

**Comment by afkcodes** [comment]
Thanks for the update I know I am not a founding member but can I join you, folks, I think I can make a difference. 
Regarding the PR i will update it by tomorrow.

**Comment by afkcodes** [comment]
in my opinion, we don't need a full-fledged design right now we can start taking references from any dribble design modify the way we want and in the way, once someone is willing to contribute as a designer we will revamp.

**Comment by Jarmos-san** [comment]
> ... but can I join you, folks, I think I can make a difference

Of course! Any sort of contributions to any of the projects in this community are welcome! Please feel free to join our Discord channel for further discussions & general chit-chat.

> ... we don't need a full-fledged design right now ... taking references from any dribble design modify the way we want ... contribute as a designer we will revamp

That's the plan for now as well, release & deploy a **VERY** rudimentary landing page for the first iteration. It should be enough to get the name of the community out there. So, all that's required for now is a minimal MVP with enough SEO for Google to rank the page well.

And thank you if you could help us with your Dribble projects! None of us are designers as such we need help from others who're proficient in web design. If you would like to further discuss about design ideas, feel to respond to #6 (_discussion thread_).

**Comment by afkcodes** [comment]
Got the point what I was asking is that I think we didn't discuss the website being live and running again on discord please correct me if I am wrong not being so active there for a while.

**Comment by afkcodes** [comment]
Pinged you on discord, please have a look lets make this big.

**Comment by Jarmos-san** [comment]
I made an informal announcement last week & discussed it with the founders only today afternoon. I'm organizing certain things related to the [developersIndia GitHub org](https://github/developersIndia/developersIndia) along with @Bhupesh-V for now. Once it's all done, I'll make a formal announcement for collaboration efforts in our Discord server. So, keep an eye-out for it & let us know if you've any questions.

As for the "core members", there's nothing of that sort for now. developersIndia is a community & everything related to it is community-led. We, as-in me, Bhupesh, Sid & the others are just here to provide a roadmap for the community with their ideas & projects.

I suggest discussing about it in the Discord channel or the [subreddit](https://www.reddit.com/r/developersIndia) or in a [GitHub Discussion](https://github.com/developersIndia/developersIndia.in/discussions) to keep this PR on-topic.

**Comment by Jarmos-san** [comment]
@afkcodes are you still interested in pursuing this PR? If so, let me know so that I can help you guide through what needs to remain & what doesn't.

**Comment by Jarmos-san** [comment]
Don't you've the perms to fork the project & send a PR? If so let me know because we're in the process of reorganizing the developersIndia GitHub Organization.

Else if you want, send in a new PR & link #13 to close it. Let me know when you do it, so that I can close this current PR in favor of the new one.

**Comment by afkcodes** [comment]
lets close this PR i will create a new one.

**Comment by afkcodes** [comment]
PR has been raised #23 in support of this. lets close this.

**Pull request closed without merging**
